#Apartado de conexi\u00c3\u00b3n a la base de datos
spring.application.name=AppSegurity
#URL de la base de datos MongoDB (Railway leera\u00a1 la variable de entorno MONGO_URI)
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/app_supervision}

app.seeders.enabled=${SEEDERS_ENABLED:true}



# Configuracion de Correo Electronico (Spring Mail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nbohorquezm@unicesar.edu.co
spring.mail.password=toqschfajqkobgkv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

