package com.example.AppSegurity.Enums;

public enum ClaseAlerta {
    AUDIO, VISION, PROCESO, TECLADO, OBJETO, ENTORNO, CAMARA_OBSTRUIDA, CONTROL_REMOTO, APP_TERMINADA, SESION_DUPLICADA, DESCONEXION_REINCIDENTE, DESCONEXION_PROLONGADA
}
